import pyautogui
import time

# Képernyő méretel
SCREEN_W, SCREEN_H = pyautogui.size()
SCREEN_W_HALF, SCREEN_H_HALF = SCREEN_W/2, SCREEN_H/2


# Alap Játékos értékek
BASE_COLOR = [150,150,150]
BASE_SHOOTING_POWER = 750
BASE_SIZE = 300
BASE_THICKNESS = 5
BASE_SPEED = 500

# Növelés mértéke
PLUS_SIZE = 1.5
PLUS_SPEED = 2
PLUS_COLOR = 100
PLUS_SHOOTING_POWER = 400

# Csökkentés mértéke
MINUS_SIZE = 1.2
MINUS_SPEED = 1.5
MINUS_COLOR = 100
MINUS_SHOOTING_POWER = 300

# Labda színek
BALL_COLORS = ["white", "red", "blue", "green", "pink", "purple", "black", "yellow", "orange"]

# Betűk paraméterei
SCORE_FONT_SIZE = 144
SCORE_FONT_COLOR = "white"
SCORE_FONT_HEIGHT = 100
SCORE_FONT_MARGIN = 300

SCORE_LIMIT_FONT_SIZE = SCORE_FONT_SIZE // 3
SCORE_LIMIT_FONT_COLOR = "white"

BONUS_FONT_SIZE = 32
BONUS_FONT_COLOR_PLUS = "green"
BONUS_FONT_COLOR_MINUS = "red"
BONUS_FONT_HEIGHT = 0
BONUS_FONT_MARGIN_INNER = 300
BONUS_FONT_MARGIN_OUTER = 600

# Labda értékek
BALL_SPEED = 400
BALL_SIZE = (30,30)
BALL_COLOR = "white"
BALL_WAIT = 300

# Labda effektek
BALL_EFFECT_SIZE = 20
BALL_EFFECT_RANDOM = True
BALL_EFFECT_LIFE = 200

# Játék vége
SCORE_LIMIT_BOOL = True
SCORE_LIMIT = 15
TIME_LIMIT_BOOL = True
TIME_LIMIT = 2
TIME_FONT_SIZE = 50
TIME_X = SCREEN_W_HALF
TIME_Y = SCREEN_H-TIME_FONT_SIZE/2
